language: php

php:
  - 7.0
  - 7.1
cache:
  directories:
  - vendor

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpcs src/ --standard=ruleset.xml
  - phpunit --configuration phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email:
    - joe@fluxoft.com
