language: php

php:
  - 5.6
cache:
  directories:
  - vendor

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpcs src/ --standard=ruleset.xml
  - phpunit --configuration phpunit.xml.dist --coverage-text

notifications:
  email:
    - joe@fluxoft.com
